---
services:
  base:
    image: dev-base:${IMAGE_TAG}
    build:
      context: ./base

  tools:
    image: dev-build-tools:${IMAGE_TAG}
    build:
      context: ./tools
      additional_contexts:
        builder_base_image: service:base

  tools-go:
    image:  dev-build-tools-go:${IMAGE_TAG}
    build:
      context: ./tools
      dockerfile: Dockerfile.go

  tools-claude:
    image: dev-build-tools-claude:${IMAGE_TAG}
    build:
      context: ./tools
      dockerfile: Dockerfile.claude

  tools-goss:
    image: dev-build-tools-goss:${IMAGE_TAG}
    build:
      context: ./tools
      dockerfile: Dockerfile.goss

  go:
    image: dev-go:${IMAGE_TAG}
    build:
      context: ./go
      args:
        GO_VERSION: 1.26.0
      additional_contexts:
        builder_base_image: service:base
        builder_tools_image: service:tools
        builder_tools_go_image: service:tools-go
        builder_tools_claude_image: service:tools-claude

  python:
    image: dev-python:${IMAGE_TAG}
    build:
      context: ./python
      args:
        PYTHON_VERSION: "3.14"
      additional_contexts:
        builder_base_image: service:base
        builder_tools_image: service:tools
        builder_tools_claude_image: service:tools-claude
