FROM docker:cli as docker-cli
FROM library/debian:stable-slim
ARG GOSS_VERSION=latest
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker-compose /usr/local/bin/
RUN \
  export DEBIAN_FRONTEND=noninteractive && \
  apt update && apt -y install curl
RUN \
  curl -fsSL https://github.com/goss-org/goss/releases/download/v${GOSS_VERSION}/goss_${GOSS_VERSION}_linux_x86_64.tar.gz | \
    tar zxf - -C /usr/local/bin/ goss && \
  curl -fsSL https://github.com/goss-org/goss/releases/download/v${GOSS_VERSION}/dgoss -o /usr/local/bin/dgoss && \
  chmod +rx /usr/local/bin/goss /usr/local/bin/dgoss
ENV \
  GOSS_FILES_PATH=/tests \
  GOSS_FILES_STRATEGY=cp